const getAllGenres = {
  boevik: "боевик",
  fentezi: "фэнтези",
  fantastika: "фантастика",
  triller: "триллер",
  voennyj: "военный",
  detektiv: "детектив",
  komediya: "комедия",
  drama: "драма",
  uzhasy: "ужасы",
  kriminal: "криминал",
  melodrama: "мелодрама",
  vestern: "вестерн",
  biografiya: "биография",
  anime: "аниме",
  detskij: "детский",
  multfilm: "мультфильм",
  "film-nuar": "фильм-нуар",
  "dlya-vzroslyh": "для взрослых",
  dokumentalnyj: "документальный",
  igra: "игра",
  istoriya: "история",
  koncert: "концерт",
  korotkometrazhka: "короткометражка",
  muzyka: "музыка",
  myuzikl: "мюзикл",
  novosti: "новости",
  priklyucheniya: "приключения",
  "realnoe-tv": "реальное ТВ",
  semejnyj: "семейный",
  sport: "спорт",
  "tok-shou": "ток-шоу",
  ceremoniya: "церемония",
};

export default getAllGenres;
